// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKpjU6yiHp_mjnd5tv5FmlA1gbYzOM2k',
    appId: '1:517600791263:web:f1bb8d1d986b26a9b9b76a',
    messagingSenderId: '517600791263',
    projectId: 'test-app-718da',
    authDomain: 'test-app-718da.firebaseapp.com',
    storageBucket: 'test-app-718da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzI7_7xdphlYH4idVUeWAHo64H_waF6vQ',
    appId: '1:517600791263:android:a61d7aba693d7446b9b76a',
    messagingSenderId: '517600791263',
    projectId: 'test-app-718da',
    storageBucket: 'test-app-718da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcAZO0G06ngUUAqE-oKXzG-e3yWyZl5U',
    appId: '1:517600791263:ios:0e3a3db54a7e6154b9b76a',
    messagingSenderId: '517600791263',
    projectId: 'test-app-718da',
    storageBucket: 'test-app-718da.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcAZO0G06ngUUAqE-oKXzG-e3yWyZl5U',
    appId: '1:517600791263:ios:0e3a3db54a7e6154b9b76a',
    messagingSenderId: '517600791263',
    projectId: 'test-app-718da',
    storageBucket: 'test-app-718da.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKpjU6yiHp_mjnd5tv5FmlA1gbYzOM2k',
    appId: '1:517600791263:web:4b16bf8f4cf1dae6b9b76a',
    messagingSenderId: '517600791263',
    projectId: 'test-app-718da',
    authDomain: 'test-app-718da.firebaseapp.com',
    storageBucket: 'test-app-718da.appspot.com',
  );
}
